#!/bin/sh
# Usage: gen_nhlua.sh <src_root> <build_dir>
set -e
SRC="$1"
BUILD="$2"
OUT="$SRC/include/nhlua.h"
LUA="$SRC/submodules/lua"

printf '/* nhlua.h - generated by meson build */\n' > "$OUT"
printf '#include "../submodules/lua/lua.h"\n' >> "$OUT"
sed -e '/(lua_error)/!d' \
    -e '/(lua_error)/s/LUA_API/ATTRNORETURN LUA_API/1' \
    -e '/(lua_error)/s/;/ NORETURN;/1' < "$LUA/lua.h" >> "$OUT"
printf '#include "../submodules/lua/lualib.h"\n' >> "$OUT"
printf '#include "../submodules/lua/lauxlib.h"\n' >> "$OUT"
printf '/*nhlua.h*/\n' >> "$OUT"
cp "$OUT" "$BUILD/nhlua.h"
